server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # автоматическая маршрутизация по именам из Eureka
          lower-case-service-id: true
      routes:
        - id: clientService
          uri: lb://clientService  #lb:// = load balancing через Eureka
          predicates:
            - Path=/api/clients/**
          filters:
            - StripPrefix=1  # Убирает /api из пути при проксировании

        - id: orderService
          uri: lb://orderService
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


