server:
  port: 8081

spring:
  application:
    name: clientService
  
  # ====== НАСТРОЙКИ БАЗЫ ДАННЫХ ======
  datasource:
    # ЯВНО указываем URL БЕЗ переменных окружения для теста
    url: jdbc:postgresql://localhost:5432/clientservice  # ← в lowercase
    username: postgres
    password: 233122
    driver-class-name: org.postgresql.Driver  # ← ОБЯЗАТЕЛЬНО!
    
    # Hikari Connection Pool
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: ClientServiceHikariCP
  
  # ====== JPA НАСТРОЙКИ ======
  jpa:
    hibernate:
      ddl-auto: update  # создает таблицы автоматически
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false

# ====== EUREKA ======
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}
    hostname: localhost
    prefer-ip-address: true
