server:
  port: 8081

spring:
  application:
    name: clientService

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/clientservice}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:233122}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      connection-timeout: 30000
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        default_schema: public
        format_sql: true
    open-in-view: false

  docker:
    compose:
      enabled: false  # ← ВЫКЛЮЧАЕМ автозапуск

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30  # каждые 30 сек "я жив!"
